version: '3'

services: 
    mongodb:
        image:  mongo
        container_name: mongoDB
        restart: always
        ports: 
            - "27018:27017"
        
    redis:
        image: redis
        container_name: redis
        restart: always
        ports: 
            - "6380:6379"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitMQ
        restart: always
        ports: 
            - "15673:15672"
       