version: '3'

services: 
    mongodb:
        image:  mongo:4.0
        container_name: mongoDB
        restart: always
        ports: 
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "root"
            MONGO_INITDB_DATABASE: mydatabase
        
    redis:
        image: redis
        container_name: redis
        restart: always
        ports: 
            - 6380:6379

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitMQ
        restart: always
        ports: 
            - 15673:15672 #UI
            - 5673:5672
        
       